// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            ProdutoClienteManutencao = new HashSet<ProdutoClienteManutencao>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Required]
        [Column("nome_cliente")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeCliente { get; set; }
        [Required]
        [Column("endereco")]
        [StringLength(50)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Required]
        [Column("bairro")]
        [StringLength(50)]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(20)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [Required]
        [Column("email")]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("numero_endereco")]
        [StringLength(10)]
        [Unicode(false)]
        public string NumeroEndereco { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<ProdutoClienteManutencao> ProdutoClienteManutencao { get; set; }
    }
}