// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    [Table("Produto_Cliente_Manutencao")]
    public partial class ProdutoClienteManutencao
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column("idProduto")]
        public int IdProduto { get; set; }
        [Column("dataCadastro", TypeName = "datetime")]
        public DateTime DataCadastro { get; set; }
        [Column("dataFinalizacao", TypeName = "datetime")]
        public DateTime DataFinalizacao { get; set; }
        public bool Feito { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("ProdutoClienteManutencao")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey("IdProduto")]
        [InverseProperty("ProdutoClienteManutencao")]
        public virtual Produto IdProdutoNavigation { get; set; }
    }
}